name: C++

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: checkout

      - name: install pybind11
        run: git clone https://github.com/pybind/pybind11.git

      - name: configure
        run: cmake -S ./ -B build

      - name: build
        run: cmake --build build

      - name: test
        run: ctest --tests ./build